<?php 
    
?>

<h1 style="margin-top: 10px; text-align:center">Pokédex</h1>
<hr>
    <div class="card-container">
        <?php for ($i = 0; $i < $this->pokemonsLength; $i++) { ?>
            <div class="card-item">
                <img src="<?php echo $this->imagem ?>" class="img" alt="...">
                <div>
                    <p><strong> Nº <?php echo $this->numero ?> </strong></p>
                    <h4> <?php echo $this->nome ?> </h4>
                    <?php foreach($this->data->types as $idx2 => $type) {  ?>
                        <p class="tipo"><?php echo $type->type->name ?></p>
                    <?php } ?>
                </div>
            </div>
        <?php $this->id++; $this->getPokemonById($this->id); } ?>
    </div>